// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP _JGNsc_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// ThresholdPartCorr
double ThresholdPartCorr(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _JGNsc_ThresholdPartCorr(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ThresholdPartCorr(x, y));
    return rcpp_result_gen;
END_RCPP
}
// ThresholdPartCorrList
double ThresholdPartCorrList(List x, List y);
RcppExport SEXP _JGNsc_ThresholdPartCorrList(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ThresholdPartCorrList(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JGNsc_timesTwo", (DL_FUNC) &_JGNsc_timesTwo, 1},
    {"_JGNsc_ThresholdPartCorr", (DL_FUNC) &_JGNsc_ThresholdPartCorr, 2},
    {"_JGNsc_ThresholdPartCorrList", (DL_FUNC) &_JGNsc_ThresholdPartCorrList, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_JGNsc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
