# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_rowSums <- function(X) {
    .Call(`_JGNsc_arma_rowSums`, X)
}

arma_colSums <- function(X) {
    .Call(`_JGNsc_arma_colSums`, X)
}

arma_rowMeans <- function(X) {
    .Call(`_JGNsc_arma_rowMeans`, X)
}

arma_colMeans <- function(X) {
    .Call(`_JGNsc_arma_colMeans`, X)
}

BinMatrix <- function(x) {
    .Call(`_JGNsc_BinMatrix`, x)
}

MaxAbsMatrix <- function(x) {
    .Call(`_JGNsc_MaxAbsMatrix`, x)
}

frobeniousNorm <- function(x) {
    .Call(`_JGNsc_frobeniousNorm`, x)
}

oneNorm <- function(x) {
    .Call(`_JGNsc_oneNorm`, x)
}

softThresh_cpp <- function(x, threshold = 0.5) {
    .Call(`_JGNsc_softThresh_cpp`, x, threshold)
}

gasdev <- function(r = 1) {
    .Call(`_JGNsc_gasdev`, r)
}

JGNsc_cont_cpp <- function(y, minCell, iter = 5000L, warm = 2000L, stepsize = 0.5, dropThreshold = 0.7, a1 = 2, b1 = 1, a2 = 0.001, b2 = 1e8, a3 = 0.001, b3 = 1e8) {
    .Call(`_JGNsc_JGNsc_cont_cpp`, y, minCell, iter, warm, stepsize, dropThreshold, a1, b1, a2, b2, a3, b3)
}

mcImpute_cpp <- function(data, preprocess = TRUE, eps = 1e-12, normfac = 1, insweep = 20L, tol = 1e-4, decfac = 0.7, min_count = 1L, min_cells = 1L, verbose = FALSE) {
    .Call(`_JGNsc_mcImpute_cpp`, data, preprocess, eps, normfac, insweep, tol, decfac, min_count, min_cells, verbose)
}

