# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call(`_JGNsc_timesTwo`, x)
}

#' Thresholding a Partial correlation matrix
#'
#' @param x Gaussian matrix with samples x genes
#' @param y the estimated partial correlation matrix
#' @export
ThresholdPartCorr <- function(x, y) {
    .Call(`_JGNsc_ThresholdPartCorr`, x, y)
}

#' Thresholding a list of Partial correlation matrices
#'
#' @param x a list of Gaussian matrices with samples x genes
#' @param y a list of the estimated partial correlation matrices
#' @export
ThresholdPartCorrList <- function(x, y) {
    .Call(`_JGNsc_ThresholdPartCorrList`, x, y)
}

